---
- name: Create a new user on Linux with a password
  hosts: docker_hosts
  become: true
  vars:
    # These are default variables. The AWX Survey will override them.
    new_username: "default_user"
    user_shell: "/bin/bash"
    plaintext_password: "MySecurePassword123"
    password_salt: "ubuntu2404salt"

  tasks:    
    - name: Ensure the user exists with the secure password hash
      ansible.builtin.user:
        name: "{{ new_username }}"
        state: present
        shell: "{{ user_shell }}"
        create_home: true
        password: "{{ plaintext_password | ansible.builtin.password_hash('sha512', password_salt) }}"
        update_password: on_create
      no_log: true

    - name: Add the user to the sudo group
      ansible.builtin.user:
        name: "{{ new_username }}"
        groups: sudo
        append: true

    - name: Enable password authentication in SSH configuration
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication yes'
        state: present
      notify: Reload SSH socket

  handlers:
    - name: Reload SSH socket
      ansible.builtin.systemd_service:
        name: ssh.socket
        state: restarted
        daemon_reload: true
