---
version: 3

images:
  base_image:
    name: docker.io/almalinux/10-minimal:10.1-20260524

dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml

options:
  package_manager_path: /usr/bin/microdnf
  skip_ansible_check: true
  relax_passwd_permissions: true

additional_build_steps:
  prepend_base:
    - RUN microdnf install -y tar openssl python3 python3-pip git
    - RUN $PYCMD -m pip install --upgrade pip
    - RUN $PYCMD -m pip install passlib ansible-core kubernetes proxmoxer netapp-lib requests jsonpatch PyYAML
  append_base:
    - RUN mkdir -p /tmp/src && echo "" > /tmp/src/requirements.txt
    - RUN curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    - RUN chmod 700 get_helm.sh
    - RUN VERIFY_CHECKSUM=false ./get_helm.sh
    - RUN rm get_helm.sh
